# Docs see here:
# https://aka.ms/yaml


pr:
  autoCancel: true # indicates whether additional pushes to a PR should cancel in-progress runs for the same PR. Defaults to true

variables:
  choco_cache: C:/ProgramData/chocolatey
  vcpkg_cache: C:/vcpkg/installed

jobs:
- job: 'win_vs2017'
  displayName: 'Windows (VS2017)'
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    CC_NAME: Visual Studio 15 2017
    CC_SHORTNAME: VS2017
    GENERATOR: Visual Studio 15 2017
    FORCE_CXX: OFF
  steps:
  - checkout: self
    submodules: recursive

  - task: CacheBeta@0
    inputs:
      key: $(Build.SourcesDirectory)/tools/azure-devops/install.ps1
      path: $(choco_cache)
    displayName: Cache Choco
  - task: CacheBeta@0
    inputs:
      key: $(Build.SourcesDirectory)/tools/azure-devops/install.ps1
      path: $(vcpkg_cache)
    displayName: Cache vcpkg

  - powershell: ./tools/azure-devops/install.ps1
    displayName: Install Requirements
  - powershell: ./tools/azure-devops/build.ps1
    displayName: "Build: $(CC_NAME)"

  - publish: ./open62541-$(CC_SHORTNAME)-static.zip
    artifact: open62541-$(CC_SHORTNAME)-static
    displayName: "Publish Artifact: open62541-$(CC_SHORTNAME)-static"

  - publish: ./open62541-$(CC_SHORTNAME)-dynamic.zip
    artifact: open62541-$(CC_SHORTNAME)-dynamic
    displayName: "Publish Artifact: open62541-$(CC_SHORTNAME)-dynamic"


- job: 'win_msys64'
  displayName: 'Windows (msys64)'
  pool:
    vmImage: 'windows-latest'
  variables:
    CC_NAME: MinGW Makefiles
    CC_SHORTNAME: mingw
    GENERATOR: MinGW Makefiles
    FORCE_CXX: OFF
    MSYS2_ROOT: C:/msys64
  steps:
  - checkout: self
    submodules: recursive
  - task: CacheBeta@0
    inputs:
      key: $(Build.SourcesDirectory)/tools/azure-devops/install.ps1
      path: $(choco_cache)
    displayName: Cache Choco

  - powershell: ./tools/azure-devops/install.ps1
    displayName: Install Requirements
  - powershell: ./tools/azure-devops/build.ps1
    displayName: "Build: $(CC_NAME)"
    errorActionPreference: continue # Nodeset Compiler prints to stderror

  - publish: ./open62541-$(CC_SHORTNAME)-static.zip
    artifact: open62541-$(CC_SHORTNAME)-static
    displayName: "Publish Artifact: open62541-$(CC_SHORTNAME)-static"
    
  - publish: ./open62541-$(CC_SHORTNAME)-dynamic.zip
    artifact: open62541-$(CC_SHORTNAME)-dynamic
    displayName: "Publish Artifact: open62541-$(CC_SHORTNAME)-dynamic"



- job: 'win_clang'
  displayName: 'Windows (clang)'
  pool:
    vmImage: 'windows-latest'
  variables:
    CC_NAME: Clang
    CC_SHORTNAME: clang-mingw
    GENERATOR: MinGW Makefiles
    FORCE_CXX: OFF
    MSYS2_ROOT: C:/msys64
  steps:
  - checkout: self
    submodules: recursive
  - task: CacheBeta@0
    inputs:
      key: $(Build.SourcesDirectory)/tools/azure-devops/install.ps1
      path: $(choco_cache)
    displayName: Cache Choco

  - powershell: ./tools/azure-devops/install.ps1
    displayName: Install Requirements
  - powershell: ./tools/azure-devops/build.ps1
    displayName: "Build: $(CC_NAME)"
    errorActionPreference: continue # Nodeset Compiler prints to stderror

  - publish: ./open62541-$(CC_SHORTNAME)-static.zip
    artifact: open62541-$(CC_SHORTNAME)-static
    displayName: "Publish Artifact: open62541-$(CC_SHORTNAME)-static"

  - publish: ./open62541-$(CC_SHORTNAME)-dynamic.zip
    artifact: open62541-$(CC_SHORTNAME)-dynamic
    displayName: "Publish Artifact: open62541-$(CC_SHORTNAME)-dynamic"
